version: '3.8'

services:
  bot:
    build: .
    container_name: bot
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data: